camel:
  springboot:
    name: OrderService
  rest:
    binding-mode: json
     
  component:
    servlet:
      mapping:
        context-path: /api/*

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/orderdb
    username: sa
    password: sa
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
     
 
# enable json binding mode
#camel.rest.binding-mode=json
# lets enable pretty printing json responses
#camel.rest.data-format-property.prettyPrint=true
# to reconfigure the camel servlet context-path mapping to use /api/* instead of /camel/*
#camel.component.servlet.mapping.context-path=/api/*
